classdef Layer < definitions.CIFWriter & definitions.materials.Material
    % The Layer class can be used to generate information of a layer in the mask design. The instance
    % of the class should also be used in the creation of geometries in different symbols.
    % To get a valid instance of the Layer class, instantiate a CIFFile class and call the
    % CIFFile.createLayer method.
    properties (SetAccess = private)
        layerId (1, 1) uint32                   % The id of the layer (generated by a CIFFile instance)
        name string                             % The name of the layer (as used by CleWin)
    end
    
    methods (Static)
        function noLayer = NoLayer()
            % NOLAYER Get a layer that should not be used, but is used as a general placeholder
            noLayer = definitions.Layer(-1, -1, "NOLAYER");
        end
    end
    
    methods
        function obj = Layer(fileHandle, layerId, name, materialProperties)
            % Layer Create an instance of a Layer object that is responsible for managing the information about a layer type in a CIF design.
            % Inputs:
            %   - fileHandle: The file handle to the CIF file
            %   - layerId: The id of the layer (generated by a CIFFile instance)
            %   - name: The name of the layer (as used by CleWin)
            %   - materialProperties.fillStyle: (Optional) The fill style of the material
            %   - materialProperties.fillColor: (Optional) The rgb color of the fill of the material
            %   - materialProperties.outlineStyle: (Optional) The outline style of the material
            %   - materialProperties.outlineColor: (Optional) The rgb color of the outline of the material
            arguments
                fileHandle (1, 1) int32                                                                                         % The file handle to the CIF file
                layerId (1, 1) uint32                                                                                           % The id of the layer (generated by a CIFFile instance)
                name string                                                                                                     % The name of the layer (as used by CleWin)
                materialProperties.fillStyle definitions.materials.FillStyle = definitions.materials.FillStyle.Solid            % (Optional) The fill style of the material
                materialProperties.fillColor (1, 3) uint8 = [0, 0, 0]                                                           % (Optional) The rgb color of the fill of the material
                materialProperties.outlineStyle definitions.materials.OutlineStyle = definitions.materials.OutlineStyle.Solid   % (Optional) The outline style of the material
                materialProperties.outlineColor (1, 3) uint8 = [0, 0, 0]                                                        % (Optional) The rgb color of the outline of the material
            end
            
            % Construct the superclasses
            obj@definitions.CIFWriter(fileHandle);
            % Use the materialproperties to instantiate the Material superclass
            obj@definitions.materials.Material(...
                materialProperties.fillStyle, ...
                materialProperties.outlineStyle, ...
                materialProperties.fillColor(1), materialProperties.fillColor(2), materialProperties.fillColor(3));
            
            obj.layerId = layerId;
            obj.name = name;
            
            % Also set the outline color
            obj.setOutlineColor(materialProperties.outlineColor(1), materialProperties.outlineColor(2), materialProperties.outlineColor(3));
        end
        
        function obj = printFile(obj)
            % line = sprintf("L L%i; (CleWin: %i %s/%s);", obj.layerId, obj.layerId, obj.name, obj.material.toString());
            line = sprintf("L L%i; (CleWin: %i %s/%s);", obj.layerId, obj.layerId, obj.name, obj.getMaterialString());
            
            obj.write(line);
        end
        
        function obj = printLayer(obj)
            % PRINTLAYER Print the layer in a symbol
            line = sprintf("L L%i;", obj.layerId);
            
            obj.write(line);
        end
        
        function iseq = eq(obj, layer)
            arguments
                obj definitions.Layer
                layer definitions.Layer
            end
            
            iseq = obj.layerId == layer.layerId && strcmp(obj.name, layer.name);
        end
        
        function isneq = neq(obj, layer)
            arguments
                obj definitions.Layer
                layer definitions.Layer
            end
            
            isneq = ~obj.eq(obj, layer);
        end
    end
end
