classdef Layer < definitions.CIFWriter
    % The Layer class can be used to generate information of a layer in the mask design. The instance
    % of the class should also be used in the creation of geometries in different symbols.
    % To get a valid instance of the Layer class, instantiate a CIFFile class and call the
    % CIFFile.createLayer method.
    properties (SetAccess = private)
        layerId double                                  % The id of the layer (generated by a CIFFile instance)
        name string                                     % The name of the layer (as used by CleWin)
        styling (1, 2) string = ["0f808080" "0f808080"] % The optional styling of the layer, uses syntax of CleWin, will be updated later
    end
    
    methods (Static)
        function noLayer = NoLayer()
            % NOLAYER Get a layer that should not be used, but is used as a general placeholder
            noLayer = definitions.Layer(-1, -1, "NOLAYER");
        end
    end
    
    methods
        function obj = Layer(fileHandle, layerId, name, styling)
            % Layer Create an instance of a Layer object that is responsible for managing the information about a layer type in a CIF design.
            % Inputs:
            %   - fileHandle: The file handle to the CIF file
            %   - layerId: The id of the layer (generated by a CIFFile instance)
            %   - name: The name of the layer (as used by CleWin)
            %   - styling: The optional styling of the layer, uses syntax of CleWin, will be updated later
            arguments
                fileHandle (1, 1) int32                                     % The file handle to the CIF file
                layerId (1, 1) uint32                                       % The id of the layer (generated by a CIFFile instance)
                name string                                                 % The name of the layer (as used by CleWin)
                styling (1, 2) string = ["0f808080" "0f808080"]             % The optional styling of the layer, uses syntax of CleWin, will be updated later
            end
            
            % Construct the superclass
            obj = obj@definitions.CIFWriter(fileHandle);
            
            obj.layerId = layerId;
            obj.name = name;
            obj.styling = styling;
        end
        
        function obj = printFile(obj)
            line = sprintf("L L%i; (CleWin: %i %s/%s %s);", obj.layerId, obj.layerId, obj.name, obj.styling(1), obj.styling(2));
            
            obj.write(line);
        end
        
        function obj = printLayer(obj)
            % PRINTLAYER Print the layer in a symbol
            line = sprintf("L L%i;", obj.layerId);
            
            obj.write(line);
        end
        
        function iseq = eq(obj, layer)
            arguments
                obj definitions.Layer
                layer definitions.Layer
            end
            
            iseq = obj.layerId == layer.layerId && strcmp(obj.name, layer.name);
        end
        
        function isneq = neq(obj, layer)
            arguments
                obj definitions.Layer
                layer definitions.Layer
            end
            
            isneq = ~obj.eq(obj, layer);
        end
    end
end
